"""Pydantic schemas for AI Travel Concierge and Guardian agent interactions."""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AgentMessage(BaseModel):
    """Chat message exchanged with the AI agent."""

    role: str = Field(..., description="Role: 'user', 'assistant', or 'system'")
    content: str = Field(..., description="Message text content")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentQueryRequest(BaseModel):
    """User prompt to the travel concierge agent."""

    prompt: str = Field(..., min_length=1, description="User instruction or query")
    trip_id: Optional[str] = Field(None, description="Optional associated trip ID for context")
    context: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Additional context")
    history: List[AgentMessage] = Field(default_factory=list, description="Recent conversation turns")


class TravelSafetyAlert(BaseModel):
    """Real-time guardian safety alert or travel advisory."""

    level: str = "info"  # info, warning, critical
    category: str = "general"  # weather, flight_delay, safety, health, transit
    title: str
    description: str
    location: Optional[str] = None
    recommended_action: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentQueryResponse(BaseModel):
    """Response generated by the AI agent."""

    reply: str
    suggested_actions: List[str] = Field(default_factory=list)
    safety_alerts: List[TravelSafetyAlert] = Field(default_factory=list)
    sources: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
